config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, uniqueness: true

  has_many :group_users
  has_many :groups, through: :group_users
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end
    
  def new
    @group = Group.new
    @group.users << current_user
  end
  
  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end      
  end

  def edit
    @group = Group.find(params[:id])
  end 
  
  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
    else
      render :edit
    end    
  end  
  
  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end  

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
  end 
  
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit  
    end  
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end  
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_with model: group, local:true do |f|
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    .SettingGroupForm__leftField 
      = f.label :name, "グループ名", class: "SettingGroupForm__label"        
    .SettingGroupForm__rightField    
      = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名を入力してください"
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      %label.SettingGroupForm__label チャットメンバーを追加
    .SettingGroupForm__rightField  
      = f.collection_check_boxes :user_ids, User.all, :id, :name
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField  
      = f.submit class: "SettingGroupForm__button"

app/views/groups/edit.html.haml
.SettingGroupForm
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group}

app/views/groups/index.html.haml
.Wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
.SettingGroupForm
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace2
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_main_chat.html.haml
.MainChat
  .RightHeader__group
    .RightHeader__groupInfo
      .RightHeader__groupName A
      %ul.RightHeader__memberLists 
        Member:
        %li.RightHeader__members
          test
    = link_to "Edit", '/', class: "RightHeader__editButton"
  .MessagesField
    .MessageBox
      .MessageInfo
        .MessageInfo__userName
          A
        .MessageInfo__date
          2020.2.28
      .Message
        %p.Message__content
          Hello
  .Footer
    %form.Form
      .Form__contents
        %input{class: "Form__inputContent", placeholder: "Type a message"}
        %label.Form__inputImage
          = icon('far','image', class: 'Form__icon')
          %input.Form__inputImage__hidden{type: "file"}
      %input{type: 'submit', value: 'Send', class: "Form__submit"} 

app/views/messages/_side_bar.html.haml
.SideBar
  .LeftHeader
    .LeftHeader__lists
      %h3.LeftHeader__userName
        = current_user.name
      %ul.LeftHeader__iconLists
        %li.LeftHeader__icon
          = link_to ""
          = icon('fas', 'seedling')
        %li.LeftHeader__icon
          = link_to new_group_path do
            = icon('fas', 'user-friends')
        %li.LeftHeader__icon
          = link_to edit_user_path(current_user) do 
            = icon('fas', 'cog')
  .GroupLists
    - current_user.groups.each do |group|
      .Group
        = link_to "#" do
          .Group__name 
            = group.name
          .Group__message
            メッセージはまだありません

app/views/messages/index.html.haml
.Wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'